#### ![](Homework.png)

In [76]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [60]:
epochs = 1000
learning_rate = 0.1

In [61]:
x = tf.reshape(tf.constant([0.05, 0.1]), (1, 2))
x = tf.concat([x, tf.ones((x.shape[0], 1))], axis=1)

x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.05, 0.1 , 1.  ]], dtype=float32)>

In [62]:
y = tf.constant(0.5)

In [63]:
tf.random.set_seed(1)
w1 = tf.Variable(
    tf.random.uniform((3, 2), minval=0, maxval=1)
)
w1

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[0.16513085, 0.9014813 ],
       [0.6309742 , 0.4345461 ],
       [0.29193902, 0.64250207]], dtype=float32)>

In [64]:
w2 = tf.Variable(
    tf.random.uniform((3, 1), minval=0, maxval=1)
)
w2

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[0.51010704],
       [0.44353175],
       [0.4085331 ]], dtype=float32)>

In [70]:
for i in range(epochs):
    with tf.GradientTape() as tape:
        h = tf.sigmoid(tf.matmul(x, w1))
        h = tf.concat([h, tf.ones((h.shape[0], 1))], axis=1)
        y_pred = tf.sigmoid(tf.matmul(h, w2))
        MSE = (y - y_pred)**2
        
    dMSE = tape.gradient(MSE, [w1, w2])

    w1.assign_sub(learning_rate * dMSE[0]) 
    w2.assign_sub(learning_rate * dMSE[1])
    

In [71]:
print(w1, w2, sep='\n')

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[0.16276515, 0.89989346],
       [0.6262427 , 0.43136945],
       [0.24462062, 0.6107324 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.18351413],
       [ 0.06794371],
       [-0.15148927]], dtype=float32)>


In [72]:
y_pred = tf.sigmoid(tf.matmul(h, w2))
y_pred

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.50000006]], dtype=float32)>

In [74]:
MSE = (y - y_pred)**2
MSE

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[3.5527137e-15]], dtype=float32)>