#### ![](Homework.png)

In [1]:
import tensorflow as tf
import numpy as np

In [40]:
learning_rate = 0.1

In [47]:
x = tf.reshape(tf.constant([0.05, 0.1]), (1, 2))
x = tf.concat([x, tf.ones((h.shape[0], 1))], axis=1)

x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.05, 0.1 , 1.  ]], dtype=float32)>

In [32]:
y = tf.constant(0.5)

In [33]:
tf.random.set_seed(1)
w1 = tf.Variable(
    tf.random.uniform((3, 2), minval=0, maxval=1)
)
w1

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[0.16513085, 0.9014813 ],
       [0.6309742 , 0.4345461 ],
       [0.29193902, 0.64250207]], dtype=float32)>

In [34]:
w2 = tf.Variable(
    tf.random.uniform((3, 1), minval=0, maxval=1)
)
w2

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[0.51010704],
       [0.44353175],
       [0.4085331 ]], dtype=float32)>

In [38]:
with tf.GradientTape() as tape:
    h = tf.sigmoid(tf.matmul(x, w1))
    h = tf.concat([h, tf.ones((h.shape[0], 1))], axis=1)
    y_pred = tf.sigmoid(tf.matmul(h, w2))
    MSE = (y - y_pred)**2

In [39]:
dMSE = tape.gradient(MSE, [w1, w2])
print(dMSE[0], dMSE[1], sep='\n')

tf.Tensor(
[[0.00056253 0.00044349]
 [0.00112506 0.00088698]
 [0.01125056 0.00886981]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.05377207]
 [0.06153871]
 [0.09116422]], shape=(3, 1), dtype=float32)


In [44]:
w1.assign_sub(learning_rate * dMSE[0]) 

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float32, numpy=
array([[0.1649621 , 0.90134823],
       [0.6306366 , 0.43428004],
       [0.28856382, 0.63984114]], dtype=float32)>

In [43]:
w2.assign_sub(learning_rate * dMSE[1])

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[0.4993526 ],
       [0.431224  ],
       [0.39030027]], dtype=float32)>